services:
  database:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./:/etc/nginx/conf.d
      - ./public:/var/www/html/public
  php:
    image: php:8.1.26-fpm-alpine
    volumes:
      - ./:/var/www/html
version: '3'
volumes:
  database_data: null
